allowBuilds:
  '@apollo/protobufjs': true
  '@swc/core': true
  esbuild: true

enablePrePostScripts: true
minimumReleaseAge: 1440
strictPeerDependencies: false

overrides:
  graphql: 17.0.2

packages:
  - packages/*
  - packages/foundation/tools/*
