import fs from 'node:fs/promises';

import { Types } from '@graphql-codegen/plugin-helpers';
import prettier from 'prettier';

import { WriteDefinitionsOptions } from '../models/WriteDefinitionsOptions.js';

const DEFAULT_BANNER_CONTENT: string = `/* eslint-disable */
/**
 * This file was automatically generated by @graphql-codegen/cli.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source graphql file,
 * and run the generation script to regenerate this file.
 */
`;

export default async function writeDefinitions(
  options: WriteDefinitionsOptions,
): Promise<void> {
  const bannerContent: string = options.bannerContent ?? DEFAULT_BANNER_CONTENT;

  await Promise.all(
    options.fileOutputs.map(
      async (fileOutput: Types.FileOutput): Promise<void> => {
        let sourceCode: string = bannerContent + fileOutput.content;

        if (options.prettierConfig !== undefined) {
          sourceCode = await prettier.format(sourceCode, {
            ...options.prettierConfig,
            parser: 'typescript',
          });
        }

        await fs.writeFile(fileOutput.filename, sourceCode);
      },
    ),
  );
}
