import { afterAll, beforeAll, describe, expect, it, vitest } from 'vitest';

vitest.mock('node:fs/promises');
vitest.mock('prettier', () => ({
  default: {
    format: vitest.fn(),
  },
}));

import fs from 'node:fs/promises';

import { Types } from '@graphql-codegen/plugin-helpers';
import prettier from 'prettier';

import { type WriteDefinitionsOptions } from '../models/WriteDefinitionsOptions.js';
import writeDefinitions from './writeDefinitions.js';

describe(writeDefinitions, () => {
  describe('when called with prettierConfig', () => {
    let optionsFixture: WriteDefinitionsOptions;
    let fileOutputsFixture: Types.FileOutput[];
    let formattedContentFixture: string;

    beforeAll(async () => {
      fileOutputsFixture = [
        {
          content: 'export interface User { id: string; }',
          filename: '/output/User.ts',
        },
        {
          content: 'export interface Post { id: string; }',
          filename: '/output/Post.ts',
        },
      ];

      optionsFixture = {
        bannerContent: '/* Custom banner */',
        fileOutputs: fileOutputsFixture,
        prettierConfig: {
          semi: true,
          singleQuote: true,
        },
      };

      formattedContentFixture = 'formatted content';

      vitest.mocked(prettier.format).mockResolvedValue(formattedContentFixture);
      vitest.mocked(fs.writeFile).mockResolvedValue(undefined);

      await writeDefinitions(optionsFixture);
    });

    afterAll(() => {
      vitest.resetAllMocks();
    });

    it('should call prettier.format() for each file', () => {
      expect(prettier.format).toHaveBeenCalledTimes(fileOutputsFixture.length);

      fileOutputsFixture.forEach((fileOutput: Types.FileOutput) => {
        expect(prettier.format).toHaveBeenCalledWith(
          optionsFixture.bannerContent + fileOutput.content,
          {
            ...optionsFixture.prettierConfig,
            parser: 'typescript',
          },
        );
      });
    });

    it('should call fs.writeFile() for each file with formatted content', () => {
      expect(fs.writeFile).toHaveBeenCalledTimes(fileOutputsFixture.length);

      fileOutputsFixture.forEach((fileOutput: Types.FileOutput) => {
        expect(fs.writeFile).toHaveBeenCalledWith(
          fileOutput.filename,
          formattedContentFixture,
        );
      });
    });
  });

  describe('when called without prettierConfig', () => {
    let optionsFixture: WriteDefinitionsOptions;
    let fileOutputsFixture: Types.FileOutput;

    beforeAll(async () => {
      fileOutputsFixture = {
        content: 'export interface User { id: string; }',
        filename: '/output/User.ts',
      };

      optionsFixture = {
        bannerContent: '/* Custom banner */',
        fileOutputs: [fileOutputsFixture],
        prettierConfig: undefined,
      };

      vitest.mocked(fs.writeFile).mockResolvedValue(undefined);

      await writeDefinitions(optionsFixture);
    });

    afterAll(() => {
      vitest.resetAllMocks();
    });

    it('should not call prettier.format()', () => {
      expect(prettier.format).not.toHaveBeenCalled();
    });

    it('should call fs.writeFile() with unformatted content', () => {
      expect(fs.writeFile).toHaveBeenCalledExactlyOnceWith(
        fileOutputsFixture.filename,
        optionsFixture.bannerContent + fileOutputsFixture.content,
      );
    });
  });

  describe('when called without bannerContent', () => {
    let optionsFixture: WriteDefinitionsOptions;
    let fileOutputsFixture: Types.FileOutput;
    let expectedBanner: string;

    beforeAll(async () => {
      expectedBanner = `/* eslint-disable */
/**
 * This file was automatically generated by @graphql-codegen/cli.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source graphql file,
 * and run the generation script to regenerate this file.
 */
`;

      fileOutputsFixture = {
        content: 'export interface User { id: string; }',
        filename: '/output/User.ts',
      };

      optionsFixture = {
        bannerContent: undefined,
        fileOutputs: [fileOutputsFixture],
        prettierConfig: undefined,
      };

      vitest.mocked(fs.writeFile).mockResolvedValue(undefined);

      await writeDefinitions(optionsFixture);
    });

    afterAll(() => {
      vitest.resetAllMocks();
    });

    it('should call fs.writeFile() with default banner', () => {
      expect(fs.writeFile).toHaveBeenCalledExactlyOnceWith(
        fileOutputsFixture.filename,
        expectedBanner + fileOutputsFixture.content,
      );
    });
  });
});
